### ISSUE TITLE
I2C_loopback example failing of Nano100KE3BN development board

### ISSUE THREAD

**Issue by akhir4z** [OpenNuvoton/Nano100B_BSP#1]
The Sample example under StdDriver, i2c_loopback is not working. 
I made the necessary connections but I keep getting Master Arbitration Lost(0x38) I2C Status code

**Comment by yachen** [comment]
Hi, Did you add pull up resistors on the I2C connection?

**Comment by akhir4z** [comment]
Added the pull up resistors and it is working fine now.
Thank you
