### ISSUE TITLE
IAR build error: Error[Pe235]: variable "__stdout" was declared with a never-completed type

### ISSUE THREAD

**Issue by DinoFive** [OpenNuvoton/Nano100B_BSP#2]
IAR version: 8.40.2

I find related code in retarget.c as below:

#if !(defined(__ICCARM__) && (__VER__ >= 6010000))
struct __FILE {
    int handle; /* Add whatever you need here */
};
#endif

FILE __stdout;
FILE __stdin;

Why not implement struct __FILE in IAR higher than 6010000？

**Comment by yachen** [comment]
IAR was still @ ver5 & 6 while we published the BSP, we'll update the driver for later versions, thanks.
